### ISSUE TITLE
Fix for 1.20.4, NetworkEvent is gone

### ISSUE THREAD

**Issue by KingofMidnight** [100MediaJavaDevTeam/CapabilitySyncer#1]
Hello is it possible to fix this up a bit for 1.20.4, it because 1.20.4 doesn't have NetworkEvent but is has CustomPayloadEvent which is similar but doesn't fully work the same, i'm trying to fix it as i typing out this issue but i so far haven't been able to get it to work, i'm a beginner coder so it makes sense i'm not good at fixing up code

btw idk if this is anything but i'm using parchmentmc so yeah idk

**Comment by KingofMidnight** [comment]
oh yeah also SimpleChannel is now in ' net.minecraftforge.network.SimpleChannel; ' instead of 
' net.minecraftforge.network.simple.SimpleChannel; '

**Comment by Nyfaria** [comment]
Hi, Sorry, but no, this project will not be updated for Forge, and its not really needed for NeoForge, so 1.20.1 will most likely be the final version of this library.
